<?php

/**
 * @file
 * Primary module hooks for Text Avatar module.
 */

use Drupal\user\UserInterface;

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function text_avatar_user_update(UserInterface $entity): void {

  $action = \Drupal::config('text_avatar.settings')->get('action');

  if (($action == 'edit_user') || ($action == 'both')) {
    \Drupal::service('text_avatar.services')->setUserPicture($entity);
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function text_avatar_user_insert(UserInterface $entity): void {

  $action = \Drupal::config('text_avatar.settings')->get('action');

  if (($action == 'new_user') || ($action == 'both')) {
    \Drupal::service('text_avatar.services')->setUserPicture($entity);
  }

}
