<?php

/**
 * @file
 * Primary module hooks for Text Avatar module.
 */

use Drupal\user\UserInterface;

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function text_avatar_user_update(UserInterface $entity): void {

  /*
   * action:
   *   0: When create a new user
   *   1: Edit a user
   *   2: Both
   */
  $action = \Drupal::config('text_avatar.settings')->get('action');

  if (($action == 1) || ($action == 2)) {
    \Drupal::service('text_avatar.services')->setUserPicture($entity);
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function text_avatar_user_insert(UserInterface $entity): void {

  /*
   * action:
   *   0: When create a new user
   *   1: Edit a user
   *   2: Both
   */
  $action = \Drupal::config('text_avatar.settings')->get('action');

  if (($action == 0) || ($action == 2)) {
    \Drupal::service('text_avatar.services')->setUserPicture($entity);
  }

}
