# Schema for the configuration form of the Text Avatar module.

text_avatar.settings:
  type: config_object
  label: 'Text avatar config'
  mapping:
    folder:
      type: text
      label: 'Folder'
    imagetype:
      type: text
      label: 'Image Type'
    action:
      type: text
      label: 'Generate avatar when'
